spring:
  application:
    name: chope
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.40.130:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
